server.port=${SERVER_PORT:8080}

logging.level.root=INFO
logging.level.com.jackalcode.bootforge=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
