server.port=${SERVER_PORT:8080}

logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.jackalcode.bootforge=${LOG_LEVEL_BOOTFORGE:INFO}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
